import Head from "next/head";
import React, { useEffect } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import RegisterForm from "@/components/RegisterForm";

export default function Register() {
  const { data: session, status } = useSession();
  const Router = useRouter();

  useEffect(() => {
    if (session?.user && status !== "loading") {
      Router.push("/");
    }
  }, [session, Router, status]);

  return (
    <div>
      <Head>
        <title>ChitChat-Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RegisterForm />
    </div>
  );
}
